---
- name: Install repository
  yum:
    name: "{{ item }}"
  with_items: "{{ repository }}"

- name: Install postgresql
  yum:
    name: "{{ item }}"
  with_items: "{{ packages }}"

- name: initdb
  command: /usr/pgsql-{{ postgresql_version }}/bin/postgresql-{{ postgresql_version }}-setup initdb

- name: Start postgres
  service:
    name: postgresql-{{ postgresql_version }}
    state: started
    enabled: yes 
