---
- name: Install repository
  yum:
    name: "{{ item }}"
  with_items: "{{ rh7_repository }}"

- name: Install postgresql
  yum:
    name: "{{ item }}"
  with_items: "{{ packages }}"

- name: Initialize the database
  command: /usr/pgsql-{{ postgresql_version }}/bin/postgresql{{ postgresql_version_terse }}-setup initdb
  notify: Restart postgresql
