---
postgresql_version: 12

repository: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

packages:
  - postgresql{{ postgresql_version }}
  - postgresql{{ postgresql_version }}-server
